## Travis CI configuration for the ansible-xenserver-module library.
##
##   <https://travis-ci.org/mdklatt/ansible-xenserver-module>
##
language: python

python:
  - "2.7"

branches:
  only:
    - master
    - dev

sudo: false

install:
  - pip install -r requirements.txt -r test/requirements.txt

env:
  - ANSIBLE_LIBRARY=src

script:
  - pytest --verbose --ansible-host-pattern=localhost test/
